name: Filestash
version: "dev"
slug: filestash
description: "Filestash file manager with integrated OnlyOffice Document Server"
url: https://github.com/DerPfandadler/filestash
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
init: false
options:
  application_url: ""
  gdrive_client_id: ""
  gdrive_client_secret: ""
  dropbox_client_id: ""
  onlyoffice_url: "http://localhost:8088"
  filestash_port: 8334
  onlyoffice_port: 8088
schema:
  application_url: str
  gdrive_client_id: str
  gdrive_client_secret: str
  dropbox_client_id: str
  onlyoffice_url: str
  filestash_port: int
  onlyoffice_port: int